[package]
name = "multisig-native"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "1.5.1"
borsh-derive = "1.5.1"
solana-program = "=2.0.4"
solana-security-txt = "1.1.1"

[lib]
crate-type = ["cdylib", "lib"]
